"""phase2 corrections

Revision ID: e7a26d9cc398
Revises: 7695db33fad1
Create Date: 2026-08-23 05:45:03.941949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a26d9cc398'
down_revision: Union[str, Sequence[str], None] = '7695db33fad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_invoice_id', sa.String(length=20), nullable=False),
    sa.Column('stock_code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('customer_external_id', sa.String(length=32), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('cancellation_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancellations_customer_external_id'), 'cancellations', ['customer_external_id'], unique=False)
    op.create_index(op.f('ix_cancellations_external_invoice_id'), 'cancellations', ['external_invoice_id'], unique=False)
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('order_items', sa.Column('line_revenue', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('orders', 'is_cancelled')
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.add_column('orders', sa.Column('is_cancelled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'line_revenue')
    op.drop_column('customers', 'updated_at')
    op.drop_index(op.f('ix_cancellations_external_invoice_id'), table_name='cancellations')
    op.drop_index(op.f('ix_cancellations_customer_external_id'), table_name='cancellations')
    op.drop_table('cancellations')
    # ### end Alembic commands ###
